short a;
int short b;
short int c;
unsigned short d;
short unsigned e;
int unsigned short f;
unsigned int short g;
unsigned short int h;
int short unsigned i;
short int unsigned j;
short unsigned int k;
signed short l;
short signed m;
int signed short n;
signed int short o;
signed short int p;
int short signed q;
short int signed r;
short signed int s;
